### ISSUE TITLE
Bump version for stable support in packagist 

### ISSUE THREAD

**Issue by jakemcgraw** [thephpleague/statsd#15]
Can't utilize the addition of ```League\Statsd\Client::set()``` without lowering stability to ```dev```. Please tag a new stable version of this client and release on packagist.

**Comment by dfreudenberger** [comment]
I'd like to second this.

@marcqualie could you give an estimation on when you'll be able to do this?

**Comment by danalloway** [comment]
I'd like to bump this as well.
Based on all the things that have been added, a version bump is very much needed!

:+1:

**Comment by cvanschalkwijk** [comment]
:+1:

**Comment by thors1982** [comment]
I concur a bump in version would be greatly appreciated! Give sets to the world!

:+1:

**Comment by dfreudenberger** [comment]
@marcqualie can we do anything to speed this up a little bit? It would be great to get quicker feedback from one of the phpleague's package maintainer :)

**Comment by eversor1** [comment]
This would be very helpful: 

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by Xetoris** [comment]
:+1:

**Comment by ellio3km** [comment]
:+1:

**Comment by marcqualie** [comment]
Huge, huge apologies for the delay, somehow these Github notifications were muted.

I've now released version 1.2.0 https://github.com/thephpleague/statsd/releases/tag/1.2.0
