### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by AidasK** [thephpleague/statsd#30]
Variable `messages` should be local, it is not declared outside the function:
https://github.com/thephpleague/statsd/blob/master/src/Client.php#L298

Variable `message` is not set or used anythere:
https://github.com/thephpleague/statsd/blob/master/src/Client.php#L48

**Comment by marcqualie** [comment]
Thanks for the input!

`$this->messages` should indeed by a local variable, however, `$this->message` is used by `getLastMessage()` which is helpful for debugging and logging.
