### ISSUE TITLE
Allow port zero to be used for testing purposes

### ISSUE THREAD

**Issue by ngrevet-lightspeed** [thephpleague/statsd#41]
You are actively refusing the use of port 0 (zero) in the library:
https://github.com/thephpleague/statsd/blob/master/src/Client.php#L126
```php
if (! $port || !is_numeric($port) || $port > 65535) {
    throw new ConfigurationException($this, 'Port is out of range');
}
```

But that port has a specific use, see this documentation for example:
https://www.grc.com/port_0.htm

It would be great to be able to connect to port 0 for testing purposes.

**Comment by manavo** [comment]
Looks like this can be closed

**Comment by ngrevet-lightspeed** [comment]
👍
