### ISSUE TITLE
Release new semantic version

### ISSUE THREAD

**Issue by vgarvardt** [thephpleague/statsd#55]
It's been a long time since last semantic version was released and master has some nice and useful features fixes. It would be very helpful to issue new stable release with semantic version.

**Comment by djmarland** [comment]
I would also like this, specifically for the tags implementation which is not in the current stable release

**Comment by sc0rp10** [comment]
anyone?

**Comment by cwdt** [comment]
Also interested in a new release

**Comment by nhatthm** [comment]
+1 for a new release

**Comment by marcqualie** [comment]
I've pushed 1.5.0 to packagist.

I don't have access to the settings for this repo, someone from ThePHPLeague should either take this over or archive it due to lack of active development and maintenance.

**Comment by frankdejonge** [comment]
Thank you, @marcqualie!

**Comment by nhatthm** [comment]
Thank you guys!
